name = "city-fragrance-next"
main = ".next/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[[services]]
binding = "NEXT_SERVICE"
service = "city-fragrance-next"
